spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:6969/airport_db
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  banner:
    location: banner.txt


  custom:
    prop: "salut"